<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFrameworks>net8.0;net10.0</TargetFrameworks>	  
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>OpenID4VC.OpenID4VP</PackageId>
    <Version>1.0.0-preview.4</Version>
    <Authors>Geert Doornbos</Authors>
    <Description>OpenID for Verifiable Presentations implementation for .NET</Description>
    <PackageTags>OpenID4VC;OID4VC;OpenID4VP</PackageTags>
    <RepositoryUrl>https://github.com/openid4vc-dotnet/openid4vp</RepositoryUrl>
	<IsPackable>true</IsPackable>
    <PackageReadmeFile>README.md</PackageReadmeFile>	
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>
  	
  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.*" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.*" />
  </ItemGroup>
  	
  <ItemGroup>
    <ProjectReference Include="..\OpenID4VC.Core\OpenID4VC.Core.csproj" />
    <ProjectReference Include="..\OpenID4VP.Dcql\OpenID4VP.Dcql.csproj" />
  </ItemGroup>

  <ItemGroup>
	  <None Include="..\..\README.md" Pack="true" PackagePath="">
		  <Link>Properties\README.md</Link>
	  </None>
  </ItemGroup>
</Project>
